<p class="paypal-logo">
<?php $shortcutHtmlId = $this->getShortcutHtmlId() ?>
<?php if ($this->isOrPositionBefore()): ?>
    <span class="paypal-or"><?php echo $this->__('-OR-');?></span>
<?php endif; ?>
<a 
	<?php if (Mage::helper('paypalauth_identity')->isEnable()):?>
		href="<?php echo $this->getUrl('login/express/start', array('_secure'=>true))?>"
	<?php endif?> 
		id="<?php echo $shortcutHtmlId ?>" 
	<?php if (!$this->getIsInCatalogProduct()): ?>
		data-paypal-button="true"	
	<?php else:?>
		class="add-before-paypal"	
	<?php endif;?> 
	
	><img src="<?php echo $this->getImageUrl()?>" alt="<?php echo Mage::helper('paypal')->__('Checkout with PayPal');?>" title="<?php echo Mage::helper('paypal')->__('Checkout with PayPal');?>" /></a>
<?php if ($this->isOrPositionAfter()): ?>
    <span class="paypal-or"><?php echo $this->__('-OR-');?></span>
<?php endif; ?>
<?php if ($this->getConfirmationUrl() || $this->getIsInCatalogProduct()): ?>
<?php if ($this->getIsInCatalogProduct()): ?>
    <input type="hidden" id="pp_checkout_url" name="return_url" value="" />
<?php endif; ?>

	<?php if (!Mage::helper('paypalauth_identity')->isEnable()):?>
	<script type="text/javascript">
	//<![CDATA[
	    Event.observe('<?php echo $shortcutHtmlId ?>', 'click', function(event) {
	        <?php if ($this->getConfirmationUrl()): ?>
	            if (confirm('<?php echo Mage::helper('core')->jsQuoteEscape($this->getConfirmationMessage())?>')) {
	                this.href = '<?php echo $this->getConfirmationUrl() ?>';
	            }
	        <?php endif; ?>
	        <?php if ($this->getIsInCatalogProduct()): ?>
	       
	            $('pp_checkout_url').value = this.href;
	            productAddToCartForm.submit(this);
	            event.stop();
	        <?php endif; ?>
	    });
	//]]>
	</script>
	<?php endif; ?>
	
<?php endif; ?>
</p>