<div class="mobileSidebar">

	<a href="#" id="navLaunch"><i class="fa fa-bars" id="navLaunch"></i></a>
	
	<script type="text/javascript">
		jQuery.noConflict();
		
		// This launch Puma SideBar on form load.
		jQuery("#navLaunch").on("click",function(){
		
			jQuery.PumaSideBar({
				position: "left",  // Position
				label: "", // Initial label
				movebody: true, // if you want to push or not your page
				avatar: "/skin/frontend/custom/default/images/logo-sidebar.png", // Initial avatar.
				items: [{ // Level one
							text: "Designers",
							items: [ // Level two
									 {	text: "Alyce Paris", link: "/alyce-paris"	},
									 {	text: "Blush Prom", link: "/blush-prom"	},
									 {	text: "Cassandra Stone", link: "/cassandra-stone-prom"	},
									 {	text: "Claudine", link: "/claudine"	},
									 {	text: "Dave & Johnny", link: "/dave-and-johnny"	},
									 {	text: "Faviana", link: "/faviana"	},
									 {	text: "Flirt", link: "/flirt"	},
									 {	text: "GiGi", link: "/gigi"	},
									 {	text: "Hannah S", link: "/hannah-s"	},
									 {	text: "Holt Miami", link: "/holt-miami"	},
									 {	text: "Janique", link: "/janique"	},
									 {	text: "Jasz Couture", link: "/jasz-couture"	},
									 {	text: "La Femme", link: "/la-femme"	},
									 {	text: "Lara Designs", link: "/lara-designs"	},
									 {	text: "Mac Duggal", link: "/mac-duggal"	},
									 {	text: "Mori Lee", link: "/mori-lee"	},
									 {	text: "Night Moves", link: "/night-moves"	},
									 {	text: "Nika Formals", link: "/nika-formals"	},
									 {	text: "Panoply Designs", link: "/panoply"	},
									 {	text: "Party Time", link: "/party-time"	},
									 {	text: "Primavera Couture", link: "/primavera-couture"	},
									 {	text: "Rachel Allan", link: "/rachel-allan"	},
									 {	text: "Riva Designs", link: "/riva-designs"	},
									 {	text: "Sherri Hill", link: "/sherri-hill"	},
									 {	text: "Tarik Ediz", link: "/tarik-ediz"	},
									 {	text: "Terani Couture", link: "/terani-couture"	},
									 {	text: "Tiffany Designs", link: "/tiffany-designs"	},
									 {	text: "Tony Bowls", link: "/tony-bowls"	},
									 {	text: "Xcite", link: "/xcite-prom"	}
								   ]
						},
						{ // Level one
							text: "Dresses",
							items: [ // Level two
									 {	text: "Prom Dresses", link: "/prom-dresses"	},
									 {	text: "Short Prom", link: "/short-prom-dresses"	},
									 {	text: "High Low Prom", link: "/high-low-prom-dresses"	},
									 {	text: "Long Prom", link: "/long-prom-dresses"	},
									 {	text: "Mermaid Prom", link: "/mermaid-prom-dresses"	},
									 {	text: "Ball Prom Gowns", link: "/ball-prom-gowns"	},
									 {	text: "Print Prom", link: "/print-prom-dresses"	},
									 {	text: "Homecoming", link: "/homecoming-dresses"	},
									 {	text: "Short Homecoming", link: "/short-homecoming-dresses"	},
									 {	text: "High Low Homecoming", link: "/high-low-homecoming-dresses"	},
									 {	text: "Evening Dresses", link: "/evening-dresses"	},
									 {	text: "Formal Gowns", link: "/formal-gowns"	},
									 {	text: "Red Carpet", link: "/red-carpet-dresses"	},
									 {	text: "Special Occasions", link: "/special-occasions"	},
									 {	text: "Cocktail Dresses", link: "/cocktail-dresses"	},
									 {	text: "Club Dresses", link: "/club-dresses"	},
									 {	text: "Holiday Dresses", link: "/holiday-dresses"	},
									 {	text: "Little Black Dresses", link: "/little-black-dresses"	},
									 {	text: "Mini Dresses", link: "/mini-dresses"	},
									 {	text: "New Years Dresses", link: "/new-years-eve-dresses"	},
									 {	text: "Party Dresses", link: "/party-dresses"	},
									 {	text: "Bat Mitzvah", link: "/bat-mitzvah-dresses"	},
									 {	text: "Wedding Dresses", link: "/wedding-dresses"	},
									 {	text: "Bridesmaids", link: "/bridesmaid-dresses"	},
									 {	text: "Pageant", link: "/pageant-dresses"	},
									 {	text: "Quinceanera", link: "/quinceanera-dresses"	},
									 {	text: "Sweet Sixteen", link: "/sweet-sixteen-dresses"	}
								   ]
						},				
						{
							text: "Styles",
							items: [ // Level two
									 {	text: "Long", link: "/designer-dresses?length=1168"	},
									 {	text: "Short", link: "/designer-dresses?length=1169"	},
									 {	text: "High Low", link: "/designer-dresses?length=1167"	},
									 {	text: "A Line", link: "/designer-dresses?styles=2611"	},
									 {	text: "Ball Gown", link: "/designer-dresses?styles=2610"	},
									 {	text: "Bandage", link: "/designer-dresses?styles=2609"	},
									 {	text: "Mermaid", link: "/designer-dresses?styles=2608"	},
									 {	text: "Open Back", link: "/designer-dresses?styles=2607"	},
									 {	text: "Pleated", link: "/designer-dresses?styles=2606"	},
									 {	text: "Beaded", link: "/designer-dresses?embellishments=2596"	},
									 {	text: "Embroidery", link: "/designer-dresses?embellishments=2595"	},
									 {	text: "Feathers", link: "/designer-dresses?embellishments=2601"	},
									 {	text: "Flowers", link: "/designer-dresses?embellishments=2600"	},
									 {	text: "Lace", link: "/designer-dresses?embellishments=2594"	},
									 {	text: "Ruffles", link: "/designer-dresses?embellishments=2599"	},
									 {	text: "Sequins", link: "/designer-dresses?embellishments=2593"	},
									 {	text: "Stones", link: "/designer-dresses?embellishments=2592"	},
									 {	text: "Asymmetrical", link: "/designer-dresses?neckline=2588"	},
									 {	text: "Halter", link: "/designer-dresses?neckline=2587"	},
									 {	text: "High Neckline", link: "/designer-dresses?neckline=2586"	},
									 {	text: "Strapless", link: "/designer-dresses?neckline=2585"	},
									 {	text: "V Neck", link: "/designer-dresses?neckline=2584"	},
									 {	text: "Long Sleeve", link: "/designer-dresses?sleeve=2582"	},
									 {	text: "Medium Sleeve", link: "/designer-dresses?sleeve=2581"	},
									 {	text: "Short Sleeve", link: "/designer-dresses?sleeve=2580"	},
									 {	text: "Spaghetti Straps", link: "/designer-dresses?sleeve=2578"	},
									 {	text: "Slit", link: "/designer-dresses?slit=2598"	},
									 {	text: "Train", link: "/designer-dresses?train=2605"	},
									 {	text: "Corset", link: "/designer-dresses?waistline=2602"	},
									 {	text: "Drop Waistline", link: "/designer-dresses?waistline=2591"	},
									 {	text: "Empire", link: "/designer-dresses?waistline=2590"	},
									 {	text: "Fitted", link: "/designer-dresses?waistline=2603"	},
									 {	text: "Natural", link: "/designer-dresses?waistline=2589"	}
								   ]
						},
						{
							text: "Shoes", link: "/shoes"
						},
						{
							text: "New", link: "/new"
						},
						{
							text: "Sale", link: "/sale"
						},
						{
							text: "My Account", link: "/customer/account/"
						},
						{
                                                        text: "Sign In", link: "/customer/account/login/"
                            						},
						]
			});


		});


		</script>

</div>