<div id="mini-cart" class="block-content dropdown">
    <div class="button mini-cart-button dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="false" title="You have no items in your shopping cart.">
        <span class="cart-items">Shopping Bag (0)</span>
		<div class="arrow-container"><div class="arrow-up"></div></div>
    </div>    
                <div class="dropdown-menu">
            <div class="block-content">

                                <div class="empty">Your shopping bag is empty.</div>

            </div>
        </div>
    </div>

