<?php $items = $this->getItems() ?>
<div class="page-head">
    <h3><?php echo $this->__("All Designer")?></h3>
</div>
<div class="content">
    <?php if ($items): ?>
    <?php $width = floor(100/count($items)) ?>
    <ul class="bare-list">
    <?php foreach ($items as $letters): ?>
            <?php foreach ($letters as $letter => $options): ?>
                    <?php foreach ($options as $o): ?>
                    <li>
                        <a href="<?php echo $o['url'] ?>">
                            <?php if ($o['img']): ?>
                            <img src="<?php echo $o['img'] ?>" />
                            <?php else: ?>
                            <?php echo $this->htmlEscape($o['label']) ?>
                            <?php endif ?>
                        </a>
                        <?php if ($this->getShowCounts()) { echo '('.$o['cnt'].')'; } ?>
                    </li>
                    <?php endforeach ?>
            <?php endforeach ?>
        <?php endforeach ?>
    </ul>
    <?php endif ?>
</div>