<?php $items = $this->getItems(); $request = $this->getRequest()->getParam('designer'); ?>
<div class="left_designer left_attribute_designer">
<div class="page-head">
    
</div>
<div class="content">
</div>
</div>
    <script>
        jQuery(window).load(function(){
            if(jQuery('.Designer dd ol li').length > 0){
                jQuery('.left_attribute_designer .page-head').append('<h3><?php echo $this->__("All Designer")?></h3>');
                jQuery('.left_attribute_designer .content').append(jQuery('.Designer dd ol'));
                jQuery('.left_attribute_designer .content ol').show();
            }
        })
    </script>