<div class="title-feature-designer"><strong>Featured Designers</strong></div>
<?php foreach ($this->getItems() as $items): ?>
    <ul>
        <?php foreach ($items as $item): ?>
            <li class="amshopby-featured-wrapper">
                <a href="<?php echo $item->getUrl()?>">
                    <?php echo $this->htmlEscape($item->getTitle())?>
                </a>
            </li>
        <?php endforeach ?>
    </ul>
<?php endforeach ?>