<?php $items = $this->getItems() ?>
<div class="content">
    <?php if ($items): $i = 0;?>
    <table class="silo-table"><caption>By A-Z</caption>
        <tbody>
    <?php foreach ($items as $letters): ?>
        <?php foreach ($letters as $letter => $options): //$i++; ?>
            <?php 
				if($i%5==0){
					echo "<tr>";
				}
				echo '<td class="designerIndex '.$letter.'">';
				echo '<a href="'.$this->getUrl('designer/index/index/letter/'.$letter).'">'.$letter.'</a>';
				echo '</td>';
				if(($i+1)%count($letters)==0){
					echo '<td class="designerIndex all" colspan="3" >';
					echo '<a href="'.$this->getUrl('designer/index/index/letter/all').'">'.$this->__("View All").'</a>';
					echo '</td>';
				}
				if(($i+1)%5==0){
					echo "</tr>";
				}
				$i++;
				
				
			?>
			
        <?php endforeach ?>
    <?php endforeach ?>
        </tbody>
    </table>
    <?php endif ?>
</div>