<?php /*?><h4><?php echo $this->__('Order Tracking') ?></h4><?php */?>
<?php Mage::app()->getLayout()->getMessagesBlock()->setMessages(Mage::getSingleton('customer/session')->getMessages(true)); ?>
            <?php
                
                /*
                    This shows how to load specific fields from a record in the database.
                    1) Note the load(15), this corresponds to saying "select * from table where table_id = 15"
                    2) You can then just use the get(fieldname) to pull specific data from the table.
                    3) If you have a field named news_id, then it becomes getNewsId, etc.
                */
                /*
                $news = Mage::getModel('ordertracking/ordertracking')->load(15);
                echo $news->getNewsId();
                echo $news->getTitle();
                echo $news->getContent();
                echo $news->getStatus();
                */
                
                /*
                    This shows an alternate way of loading datas from a record using the database the "Magento Way" (using blocks and controller).
 					Uncomment blocks in /app/code/local/Namespace/Module/controllers/IndexController.php if you want to use it.

               */
                /*
                $object = $this->getOrdertracking();
                echo 'id: '.$object['test_id'].'<br/>';
				echo 'title: '.$object['title'].'<br/>';
				echo 'content: '.$object['content'].'<br/>';
				echo 'status: '.$object['status'].'<br/>';
                */            
            
            
                /*
                    This shows how to load multiple rows in a collection and save a change to them.
                    1) The setPageSize function will load only 5 records per page and you can set the current Page with the setCurPage function.
                    2) The $collection->walk('save') allows you to save everything in the collection after all changes have been made.
                */
                /*
                $i = 0;
                
                $collection = Mage::getModel('ordertracking/ordertracking')->getCollection();
                $collection->setPageSize(5);
                $collection->setCurPage(2);
                $size = $collection->getSize();
                $cnt = count($collection);
                foreach ($collection as $item) {
                    $i = $i+1;
                    $item->setTitle($i);
                    echo $item->getTitle();
                }

                $collection->walk('save');
                */
                
                /*
                    This shows how to load a single record and save a change.
                    1) Note the setTitle, this corresponds to the table field name, title, and then you pass it the text to change.
                    2) Call the save() function only on a single record.
                */
                /*
                $object = Mage::getModel('ordertracking/ordertracking')->load(1);
                $object->setTitle('This is a changed title');
                $object->save();
				*/
?> 
<?php /*?><div>
<div class="floatleft" style="width:150px; text-align:right;" >Email Address:</div><div class="floatleft"><input type="text" name="visitoremail" value="" /></div>
<div class="clear"></div>
<div class="floatleft" style="width:150px; text-align:right;">Order Id:</div><div class="floatleft"><input type="text" name="order_id" value="" /></div>
<div class="clear"></div>
<div class="floatleft" style=" width:400px; text-align:center;"><input type="submit" value="Submit" /></div>
</div><?php */?>

<?php /*?>    
<div>
	<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <form action="<?php echo $this->getUrl('ordertracking/index/view') ?>" method="post" id="form-validate">
    <fieldset>
        <legend><?php echo $this->__('Retrieve your Order here') ?></legend>
        <p><?php echo $this->__('Please enter your Email address and order id .') ?></p>
       
                <div class="input-box">
                    <label for="email_address"><?php echo $this->__('Email Address') ?> <span class="required">*</span></label><br/>
                    <input name="visitoremail" alt="visitoremail" type="text" id="email" class="required-entry validate-email  input-text" value="" />
                </div>
				<div class="clear"></div>
           
                <div class="input-box">
                    <label for="Order Id"><?php echo $this->__('Order id') ?> <span class="required">*</span></label><br/>
                    <input name="order_id" alt="order_id" type="text" id="order_id" class="required-entry  input-text" value="" />
                </div>
            
    <div class="button-set">
        <p class="required12"><?php echo $this->__('* Required Fields') ?></p>
       
	
    <button type="submit" class="form-button right"><span><?php echo $this->__('Submit') ?></span></button>
    </div>
    </fieldset>
    </form>
	</div>
    <script type="text/javascript">
    	function formsub(){	
		 if(dataForm.validator && dataForm.validator.validate()){		 	
			dataForm.submit();
		 }
	}
    </script>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('form-validate', true);
    //]]>
    </script><?php */?>
	
<div class="container-fluid" id="wrap">
    <div class="static-page-container type-site-margin help-section-container">
        <div class="row-fluid">
            <div class="help-menu span3 type-menu-block">
            	
                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('help_menu')->toHtml(); ?>
                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('help_contact')->toHtml(); ?>
			</div>

	        <div class="help-primary-content span8 push--one-sixteenth form-container">
	            <div class="contact-us-section" data-view="ContactUs">
	                <div class="fixedContainerSmall">
	                    <h3 class="text-center"><?php echo $this->__('Order Tracking') ?></h3>
	                    <form action="<?php echo $this->getUrl('ordertracking/index/view') ?>" method="post" id="form-validate">
	                        <p><?php echo $this->__('Please enter your Email address and order id .') ?></p>
	                        <div class="row-fluid">
	                            <div class="span8">
	                                <label for="email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
	                                <input name="visitoremail" alt="visitoremail" type="text" id="email" class="required-entry validate-email input-text form-input" value=""  />
	                            </div>
	                            <div class="span8">
	                                <label for="pass" class="required"><em>*</em><?php echo $this->__('Order Id') ?></label>
	                                <input name="order_id" alt="order_id" type="text" id="order_id" class="required-entry input-text form-input" value="" />
	                            </div>
	                        </div>
							
	                        <div class="row-fluid" style="margin-top:20px;">
	                            <div class="span8 offset4 submit-left">
	                                <button class="button button--inverted one-whole button--opaque js-popin-open" type="submit" name="send" id="send2"><?php echo $this->__('Track') ?></button>
	                            </div>
	                        </div>
	                        
	                        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
	                    </form>

	                </div>
	            </div>
	        </div>
	        <div class="contact-us-widget span3 push--one-eighth">
                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('help_contact')->toHtml(); ?>
	        </div>
		</div>
	</div>
</div>

	
	
	

    <script type="text/javascript">
    	function formsub(){	
		 if(dataForm.validator && dataForm.validator.validate()){		 	
			dataForm.submit();
		 }
	}
    </script>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('form-validate', true);
    //]]>
    </script>
</div>