<?php
/**
 * Shoping cart sidebar
 *
 * @see Mage_Checkout_Block_Cart_Sidebar
 */
?>
<div class="block block-minicart">

	<div id="mini-cart" class="block-content dropdown assistance">
	    <div class="button mini-cart-button dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="false" title="<?php echo $cartTitle ?>">
	        <span class="cart-items">My Account</span>
		    <div class="arrow-container"><div class="arrow-up"></div></div>
	    </div>    
	
	        <div class="dropdown-menu">
	            <div class="block-content">
	
					<ul>
						<li><a href="<?php echo Mage::getBaseUrl(); ?>customer/account/">Account Details</a></li>
						<li><a href="<?php echo Mage::getBaseUrl(); ?>sales/order/history">Orders</a></li>
						<li><a href="<?php echo Mage::getBaseUrl(); ?>customer/address/">Addresses</a></li>
						<li><a href="<?php echo Mage::helper('customer')->getLogoutUrl(); ?>">Sign Out</a></li>
					</ul>
	
	            </div>
	        </div>
	</div>

</div>