<?php
/**
 * Shoping cart sidebar
 *
 * @see Mage_Checkout_Block_Cart_Sidebar
 */
?>
<div class="block block-minicart">


	<div id="mini-cart" class="block-content dropdown">
	    <div class="button mini-cart-button dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="false" title="<?php echo $cartTitle ?>">
	        <span class="cart-items">Sign In</span>
		    <div class="arrow-container"><div class="arrow-up"></div></div>
	    </div>    
	
	        <div class="dropdown-menu">
	            <div class="block-content">
	
					<div class="block block-login" id="dropdown">
					    <form action="<?php echo $this->getUrl('customer/account/loginPost') ?>" method="post">
					        <?php echo $this->getBlockHtml('formkey'); ?>
					        <div class="block-content">
					            <input type="text" name="login[username]" id="mini-login" class="input-text" placeholder="Email"/>
					            <input type="password" name="login[password]" id="mini-password" class="input-text" placeholder="Password" />
					            <div class="actions">
					                <button type="submit" class="button"><span><span><?php echo $this->__('Sign In') ?></span></span></button>
					            </div>
					            <p class="create-account links">New Customer? <br><a href="<?php echo $this->getUrl('customer/account/create') ?>">Create an account</a></p>
					        </div>
					    </form>
					</div>
	
	            </div>
	        </div>
	</div>

</div>