<ul class="links">
                        <li class="first"><a class="top-link-cart" title="My Cart" href="/checkout/cart/">My Cart</a></li>
                                <li><a class="top-link-onestepcheckout" title="Checkout" href="/onestepcheckout/">Checkout</a></li>
                                <li><a title="Log In" href="/customer/account/login/">Log In</a></li>
                                <li><a title="Order Status" href="/sales/guest/form/">Order Status</a></li>
                                <li><a title="Help" href="/customer-service">Help</a></li>
                                <li><a title="Contact" href="/contact">Contact</a></li>
                                <li class=" last"><a title="Contact" href="http://www.promoutfitters.com/contact">718-412-1968</a></li>
            </ul>