<?php 

//load htaccess file
$base = Mage::getBaseDir('base');
$file = file_get_contents(Mage::getBaseDir('base').'/.htaccess');
?>
<div class="content-header">
	<table cellspacing="0" class="grid-header">
		<tr>
			<td><h3><?php echo $this->__('Warp Edit .htaccess')?></h3></td>
		</tr>
	</table>
</div>
<table width="100%" cellspacing="25">
	<tbody>
		<tr>
			<td width="65%">
				<div class="entry-edit img_opt">
					<div class="entry-edit-head">
						<h4>.htaccess directions</h4>
					</div>
					<fieldset>
						<div>
							<p>This will allow you to edit the htaccess file directly from Magento</p>
						</div>
						<div>
							BE CAREFUL! Editing this can affect your entire site. You want to change ONLY what you have too!
						</div>
					</fieldset>
				</div>
			</td>
		</tr>
	</tbody>
</table>

<div>
	<textarea cols='250' rows='25' id='htaccess'><?php echo $file; ?></textarea>
	<p><button onclick="saveMe()"><span><span>Submit</span></span></button></p>
</div>

<script>

	function saveMe()
	{

		var params = {};
		params['htaccess'] = $('htaccess').value;
		new Ajax.Request('<?php echo Mage::getModel('adminhtml/url')->getUrl('warp/adminhtml_index/saveht');?>', {
			method: 'post',
			parameters: params,
			onSuccess: function(transport){
				alert('.htaccess file has been saved');
				window.location.reload();
			}
		});
	}

</script>