<?php
/**
 * Customer login form template
 *
 * @see Mage_Customer_Block_Form_Login
 */
?>
<?php if (  !Mage::getStoreConfig('ajax_pro/general/enabled')
         || !Mage::getStoreConfig('ajax_pro/general/useLoginFormBlock')
         || TM_AjaxPro_Model_Action::isSearchBot()
    )
{
    return;
}
?>

<div class="account-login ajaxpro-login" style="display: none;">
<!--    <div class="page-title">
        <h1><?php echo $this->__('Login or Create an Account') ?></h1>
    </div>-->

    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="ajaxpro-login-form">
            <div class="content">
<!--                <h2><?php echo $this->__('Registered Customers') ?></h2>
                <p><?php echo $this->__('If you have an account with us, please log in.') ?></p>-->
                <ul class="form-list">
                    <li>
                        <label for="email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                        <div class="input-box">
                            <input type="text" name="login[username]" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email" title="<?php echo $this->__('Email Address') ?>" />
                        </div>
                    </li>
                    <li>
                        <label for="pass" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                        <div class="input-box">
                            <input type="password" name="login[password]" class="input-text required-entry validate-password" id="pass" title="<?php echo $this->__('Password') ?>" />
                        </div>
                    </li>
                    <?php //echo $this->getChildHtml('form.additional.info'); ?>
                </ul>
                <!--<p class="required"><?php echo $this->__('* Required Fields') ?></p>-->
            </div>
            <div class="buttons-set">
                <a href="<?php echo $this->getCreateAccountUrl() ?>" class="f-left"><?php echo $this->__('Register') ?></a>
                <a href="<?php echo $this->getForgotPasswordUrl() ?>" class="f-left"><?php echo $this->__('Forgot?') ?></a>
                <button type="submit" class="button" title="<?php echo $this->__('Login') ?>" name="send" id="send2"><span><span><?php echo $this->__('Login') ?></span></span></button>
            </div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('ajaxpro-login-form', true);

        function toggleLoginForm() {
            var el = $('ajaxpro-login-form').up('.account-login');
            if (!el) {
                return;
            }
            Effect.toggle(el, 'appear', {
                duration: .2
            });
            document.observe('click', function(e) {
                if (!Event.element(e).up('.account-login')) {
                    el.hide();
                }
            });
        };
        AjaxPro.observe('addObservers', function() {
            var el = $$('.links a:[href="<?php echo Mage::helper('customer')->getLoginUrl();?>"]').first();
            if (!el) {
                return;
            }
            el.href = '#';
            Event.observe(el, 'click', toggleLoginForm);
        });
    //]]>
    </script>
</div>
