<?php
if (   !Mage::getStoreConfig('ajax_pro/general/enabled')
    || !Mage::getStoreConfig('ajax_pro/addToCompare/enabled')
    || TM_AjaxPro_Model_Action::isSearchBot()
) {
    return;
}
$this->helper('catalog/product_compare')->calculate();
?>
<script type="text/javascript">
//<![CDATA[
AjaxPro.observe('addObservers', function() {

    $$('a').each(function(element){
        var url = element.getAttribute('href');

        if (url &&
            ((url.search('catalog/product_compare/add') != -1)
            || (url.search('catalog/product_compare/remove') != -1)
            || (url.search('catalog/product_compare/clear') != -1)
            ))
        {
            element.stopObserving('click');

            if (url.search('catalog/product_compare/remove') != -1) {
                element.setAttribute('onclick', '');
            }

            if (url.search('catalog/product_compare/clear') != -1) {
                element.setAttribute('onclick', '');
            }

            element.observe('click', function(e) {
                Event.stop(e);
                <?php if (Mage::getStoreConfig('ajax_pro/addToCompare/enabledDeleteConfirm')):?>
                var confirmation = true;
                if (url.search('catalog/product_compare/remove') != -1) {
                    confirmation = confirm('<?php echo Mage::helper('ajaxpro')->__('Are you sure you would like to remove this item from the compare products?')?>');
                }
                if (url.search('catalog/product_compare/clear') != -1) {
                    confirmation = confirm('<?php echo Mage::helper('ajaxpro')->__('Are you sure you would like to remove all products from your comparison?')?>');
                }
                if (!confirmation) {
                    return false;
                }
                <?php endif;?>

                AjaxPro.request({
                    'url'    : url,
                    'method' : 'get'
                });
                return false;
            });
            return false;
        }
    });
});

AjaxPro.observe('onLoading:catalog:product_compare', function() {

    AjaxPro.effect.opacity
        .setSelector('.block-compare').show(0.5)
        .setSelector('.block-compared').show(0.5)
    ;
});

AjaxPro.observe('onFailure:catalog:product_compare', function() {
    AjaxPro.effect.opacity
        .setSelector('.block-compare').hide()
        .setSelector('.block-compared').hide()
    ;
});

AjaxPro.observe('onComplete:catalog:product_compare', function(e) {
    var r = e.memo.response;

    if (r.messages) {
        AjaxPro.effect.message
            .setElementId('ajaxpro-addtocompare-form')
            .setMessages(r.messages)
            .show()
        ;
    }
});

//]]>
</script>

<?php if (!Mage::getStoreConfig('ajax_pro/addToCompare/enabledForm')
       || !Mage::getSingleton('log/visitor')->getId()
) {
    return;
}?>
<div id ="ajaxpro-addtocompare-form" class="ajaxpro-form" style="display:none">
    <div class="ajaxpro-message"></div>
    <button class="ajaxpro-continue-button ajaxpro-button button">
        <span><span>
            <?php echo Mage::helper('ajaxpro')->__('Continue shopping')?>
        </span></span>
    </button>
    <p class="ajaxpro-or"><?php echo Mage::helper('ajaxpro')->__('or')?></p>
    <button class="ajaxpro-button button" onclick="popWin('<?php echo Mage::getUrl('catalog/product_compare') ?>', 'compare','width=800,height=600,resizable=yes,scrollbars=yes')">
        <span><span>
            <?php echo Mage::helper('ajaxpro')->__('Compare Items');?>
        </span></span>
    </button>
</div>