<?php
    /** @var $this Mage_Catalog_Block_Product_View */
    /** @var $_helper Mage_Catalog_Helper_Output */
    $_helper = $this->helper('catalog/output');
    /** @var $_product Mage_Catalog_Model_Product */
    $_product = $this->getProduct();

    /** @var $session Mage_Checkout_Model_Session */
    $session = Mage::getSingleton('checkout/session');
    $itemId = Mage::app()->getRequest()->getParam('item');
    $item = $session->getQuote()->getItemById($itemId);
    $infoBuyRequest = @unserialize($item->getOptionByCode('info_buyRequest')->getValue());
    $pre_config_values = $this->getProduct()->getPreconfiguredValues();
?>
<script type="text/javascript">
    jQuery.noConflict();
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div class="view-popup">
    <div class="popup">
        <form action="<?php echo $this->getUrl('quickbox/product/replace'); ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
            <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
            <input type="hidden" name="related_product" id="related-products-field" value="" />
            <input type="hidden" name="replace_item_id" value="<?php echo $itemId; ?>" />

            <a href="javascript:void(0);" class="close">X</a>
            <div class="product-img-box">
                <?php echo $this->getChildHtml('media') ?>
            </div>

            <div class="product-info">
                <div class="name">
                    <b class="title"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></b>
                    <span class="pinterest">
                        <a href="//pinterest.com/pin/create/button/?media=<?php echo $this->helper('catalog/image')->init($_product, 'image'); ?>&description=<?php echo trim(Mage::registry('current_product')->getName()); ?>&url=<?php echo trim(Mage::registry('current_product')->getProductUrl()); ?>" data-pin-do="buttonPin" data-pin-config="none"><img src="//assets.pinterest.com/images/pidgets/pinit_fg_en_rect_gray_20.png" /></a>
                        <!-- Please call pinit.js only once per page -->
                        <script type="text/javascript" async src="//assets.pinterest.com/js/pinit.js"></script>
                    </span>
                    
                    <span class="wanelo">
                       <a class="wanelo-save-button"
                          href="<?php echo Mage::getBaseUrl(); ?>"
                          data-url="<?php echo $this->helper('core/url')->getCurrentUrl();?>"
                          data-title="<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>"
                          data-image="<?php echo $_product->getImageUrl(); ?>"
                          data-price="<?php echo number_format($_product->getFinalPrice(),2);?>"></a>
                    </span>
                    <script async="true" type="text/javascript" src="//cdn-saveit.wanelo.com/bookmarklet/3/save.js"></script>  
                </div>

                <?php echo $this->getPriceHtml($_product) ?>
                <?php echo $this->getChildHtml('product_type_data') ?>
                <?php echo $this->getChildHtml('alert_urls') ?>
                <?php echo $this->getTierPriceHtml() ?>
                <?php echo $this->getChildHtml('extrahint') ?>

                <div class="info-holder">
                    <p><?php echo $this->htmlEscape($_product->getData('description')); ?></p>
                    <!-- <ul class="info-list">
                        <li>Skinny, low waist, Destroyed, medium blue</li>
                        <li>100% Cotton</li>
                    </ul> -->
                    <button class="button btn-details">VIEW FULL PRODUCT DETAILS</button>
                    <div class="std product_promotion"><p><?php echo $this->htmlEscape($_product->getData('product_promotion')); ?></p></div>
                    <div class="std product_return"><p><?php echo $this->htmlEscape($_product->getData('product_return')); ?></p></div>
                    <?php echo $this->getChildHtml('other');?>
                    <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                        <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
                    <?php endif;?>

                    <div class="qty">
                    <?php if(!$_product->isGrouped()): ?>
                        <label for="qty"><?php echo $this->__('Quantity') ?></label>
                        <div class="select-styled">
                            <select name="qty" id="qty" style="width:23px;">
                                <?php
                                $qtyStock = 5;//Mage::getModel('cataloginventory/stock_item')->loadByProduct($_product)->getQty(); Need getting qty for each simple
                                foreach (range(1, (($qtyStock > 5) ? 5 : $qtyStock)) as $qty): ?>
                                <option value="<?php echo $qty; ?>"<?php if($qty == (int) $pre_config_values->getQty()/*$this->getProductDefaultQty()*/): ?> selected="selected"<?php endif ?>>
                                    <?php echo $qty ?>
                                </option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    <?php endif; ?>
                    </div>
                </div>
            </div>
            <div class="buttons">
                <button class="button" type="submit"><span><span><?php echo $this->__('Edit'); ?></span></span></button>
                <a href="<?php echo Mage::getUrl().$_product->getUrlPath(); ?>" class="a-more-details">More details</a>
            </div>
        </form>
    </div>
</div>
<script type="text/javascript">

    var $easyzoom = jQuery('.slideshow .image').easyZoom();
    var api = $easyzoom.data('easyZoom');
    jQuery('.cycle-slideshow').cycle();

    jQuery('.close').on('click', function() {
        parent.jQuery.fancybox.close();
    });

</script>