<div class="jcarousel slideshow">
    <div class="controls">
        <a class="jcarousel-prev prev" href="#">Prev</a>
        <a class="jcarousel-next next" href="#">Next</a>
      <!--   <div class="jcarousel-prev prev"></div>
        <div class="jcarousel-next next"></div>
       -->  <div class="cycle-caption"></div>
    </div>
    <div class="socials">
        <a href="" class="like">Like</a>
        <a href="" class="facebbok">Facebook</a>
        <a href="" class="pinterest">Pinterest</a>
        <a href="" class="symbaloo">Symbaloo</a>
        <a href="" class="twitter">Twitter</a>
        <a href="" class="google">G+</a>
        <a href="" class="mail">Mail</a>
    </div>
    <div class="slideshow__list">
    <?php foreach ($this->getGalleryImages() as $_image): ?>
        <div class="image easyzoom easyzoom--overlay">            
            <a href='<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile()); ?>'>
                <img src='<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(475); ?>'>
            </a>
        </div>
    <?php endforeach; ?>
    </div>
</div>
<script type="text/javascript">
    (function(){
        var slider_width,
            image = jQuery('.slideshow img'),
            slider = jQuery('.jcarousel'),
            slider_img = jQuery('.jcarousel .image'),
            controls = jQuery('.slideshow .controls');

        
        jQuery( window ).resize(function() {
            slider_width = jQuery( slider ).width();
            calc_image(slider_width);
        });
        
        jQuery('.jcarousel')
        .on('jcarousel:create jcarousel:reload', function() {
            var element = jQuery(this),
                width = element.innerWidth();
            // element.jcarousel('items').css('width', width/2 + 'px');
            calc_image(width);
        })
        .jcarousel({
            list: '.slideshow__list',
            items: '.image',
            wrap: 'circular'
        });

        jQuery('.jcarousel-prev').jcarouselControl({
            target: '-=1'
        });

        jQuery('.jcarousel-next').jcarouselControl({
            target: '+=1'
        });
        
        jQuery('.easyzoom').each(function() {
            jQuery(this).easyZoom();
        });

        
        function calc_image(width) {
            if (width > 640) {
                width = width / 2;
            }

            jQuery(slider_img).each(function(index) {
                jQuery(this).css('width', width + 'px');
            });

            controls.css({
                'left' :   width - 42 + 'px'
            });
        }
    })();
</script>