<div class="slideshow cycle-slideshow" 
            data-cycle-fx=carousel
            data-cycle-timeout=0
            data-cycle-carousel-visible=1
            data-cycle-slides="> div.image-popup"
            data-cycle-next=".next-popup"
            data-cycle-prev=".prev-popup"
            data-cycle-caption=".cycle-caption-popup"
            data-cycle-caption-template="{{slideNum}} / {{slideCount}}"
            >
    <div class="controls">
        <div class="slider__button prev-popup"></div>
        <div class="slider__button next-popup"></div>
        <div class="slider__button cycle-caption-popup"></div>        
    </div>
    <div class="socials">
        <a href="" class="like">Like</a>
        <a href="" class="facebbok">Facebook</a>
        <a href="" class="pinterest">Pinterest</a>
        <a href="" class="symbaloo">Symbaloo</a>
        <a href="" class="twitter">Twitter</a>
        <a href="" class="google">G+</a>
        <a href="" class="mail">Mail</a>
    </div>
    <?php foreach ($this->getGalleryImages() as $_image): ?>
    <div class="image-popup easyzoom easyzoom--overlay">
        <a href='<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile()); ?>'>
            <img src='<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(475); ?>' width="421" height="615" />
        </a>
    </div>
    <?php endforeach; ?>
</div>
<script type="text/javascript">
// (function(){
// 
    jQuery('.cycle-slideshow').cycle();
    jQuery('.slideshow .easyzoom').each(function(index) {
        jQuery(this).easyZoom();
    });
    
// })();
</script>