<div class="slideshow cycle-slideshow" 
            data-cycle-fx=carousel
            data-cycle-timeout=0
            data-cycle-carousel-visible=1
            data-cycle-slides="> div.image-popup"
            data-cycle-next=".next-popup"
            data-cycle-prev=".prev-popup"
            data-cycle-caption=".cycle-caption-popup"
            data-cycle-caption-template="{{slideNum}} / {{slideCount}}"
            >
    <div class="controls">
        <div class="slider__button prev-popup"></div>
        <div class="slider__button next-popup"></div>
        <div class="slider__button cycle-caption-popup"></div>
        <div class="slider__button slider__button_zoom"></div>
    </div>
    <div class="socials">
        <a href="" class="like">Like</a>
        <a href="" class="facebbok">Facebook</a>
        <a href="" class="pinterest">Pinterest</a>
        <a href="" class="symbaloo">Symbaloo</a>
        <a href="" class="twitter">Twitter</a>
        <a href="" class="google">G+</a>
        <a href="" class="mail">Mail</a>
    </div>
    <?php foreach ($this->getGalleryImages() as $_image): ?>
    <div class="image-popup easyzoom--overlay">            
        <a href='<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile()); ?>'>
            <img src='<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(475); ?>'>
        </a>
    </div>
    <?php endforeach; ?>
</div>
<div class="zoom__container" style="display: none;">
    <div class="thumb__container">
    <?php foreach ($this->getGalleryImages() as $_image): ?>
        <div class="thumb__items">
            <a href='<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile()); ?>' class="thumb__item">
                <img src='<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(475); ?>' width="65" height="98">
            </a>          
        </div>
    <?php endforeach; ?>
    </div>
    <div class="image_zoom">
        <img src="" alt="" style="top: 0; left: 0;">
    </div>
    <div class="zoom__controls">
        <div class="slider__button zoom__close"></div>
        <div class="slider__button zoom__prev"></div>
        <div class="slider__button zoom__next"></div>
        <!-- <div class="slider__button zoom__number"></div> -->
    </div>
</div>
<script type="text/javascript">
(function(){
    var $easyzoom = jQuery('.slideshow .image-popup').easyZoom();
    var api = $easyzoom.data('easyZoom');
    jQuery('.cycle-slideshow').cycle();

// Zoom
        var zoom = {
                thumb_id : 0,
                zoom_thumbs : jQuery('.thumb__items'),
                slide_count : jQuery('.thumb__items').length,
                zoom_container : jQuery('.image_zoom'),
                zoom_image : jQuery('.image_zoom').find('img'),
                selected_thumb : '',
                init: function() {
                    jQuery('.wrapper').hide();
                    jQuery('.zoom__container').prependTo(jQuery('body'));
                    jQuery('.zoom__container').css({
                        width: jQuery(window).width(),
                        height : jQuery(window).height()
                    });
                    this.show(this.thumb_id);
                    jQuery('.zoom__container').show();
                },    
                move: function () {
                    this.zoom_container.on('mousemove', function (e) {
                            e.preventDefault();
                        var zoomImage = jQuery('.image_zoom img'),
                            zoomWrapper = jQuery('.image_zoom'),
                            PageYaxis       = e.pageY,
                            wrapperHeight   = zoomWrapper.height(),
                            imgHeight       = zoomImage.outerHeight(),
                            percentageY     = (PageYaxis * 100) / wrapperHeight,
                            top             = ((-1) * (percentageY) * ((imgHeight / wrapperHeight)-1)) + "%",
                            PageXaxis       = e.pageX,
                            wrapperWidth    = zoomWrapper.width(),
                            imgWidth        = zoomImage.outerWidth(),
                            percentageX     = (PageXaxis * 100) / wrapperWidth,
                            left            = ((-1) * (percentageX) * ((imgWidth / wrapperWidth)-1)) + "%",
                            actualTop       = 0,
                            imgTop          = zoomImage.css('top');
                        
                        zoomImage.css({
                            'top': top,
                            'left': left
                        });
                    });
                },
                show: function(thumb_id) {
                    this.selected_thumb = this.zoom_thumbs.find('a').eq(thumb_id);
                    var zoom_src = jQuery(this.selected_thumb).attr('href'),
                        zoom_image = this.zoom_image;
                    
                    zoom_image.attr('src', zoom_src);

                    zoom_image.imagesLoaded(function() {
                            zoom_image.show();
                            zoom.move();
                    });

                    // this.zoom_container.append(cache_image);
                },
                close: function() {
                  jQuery('.zoom__container').hide();  
                  jQuery('.wrapper').show();
                  zoom.zoom_container.off();
                }
            };
            
// Zoom init
        jQuery('.slider__button_zoom').on('click', function (e) {
            zoom.init();
            return false;
        });
//Thumb select
        jQuery('.thumb__items').on('click', 'a', function(e) {
            this.thumb_id = zoom.zoom_thumbs.find('a').index(this);
            zoom.show(this.thumb_id);
            e.preventDefault();
        });
//Zoom close
        jQuery('.zoom__close').on('click', function(e) {
            zoom.close();
            e.preventDefault();
        });
//Previous slide
        jQuery('.zoom__prev').on('click', function(e) {
            if (zoom.thumb_id == 0) {
                zoom.thumb_id = zoom.slide_count - 1;
            }
            else {
                --zoom.thumb_id;
            }
            zoom.show(zoom.thumb_id);
            e.preventDefault();
        });
//Next slide
        jQuery('.zoom__next').on('click', function(e) {
            if (zoom.thumb_id == zoom.slide_count - 1) {
                zoom.thumb_id = 0;
            }
            else {
                ++zoom.thumb_id;
            }
            zoom.show(zoom.thumb_id);
            e.preventDefault();
        });
})();
</script>