<script>
(function(d, s, id){ 
	 var js, ref = d.getElementsByTagName(s)[0]; 
	 if (!d.getElementById(id)){ 
	 js = d.createElement(s); js.id = id; js.async = true; 
	 js.src = "//www.paypalobjects.com/js/external/paypal.v1.js"; 
	 ref.parentNode.insertBefore(js, ref); 
	 } 
}(document, "script", "paypal-js"));
</script>
<div class="m-dialog"></div>

<style>
	.m-dialog{position:fixed; left:0;top:0;width:100%;height:100%;background-color: rgba(0,0,0,0.6); display: none;z-index: 10000;}
</style>

