<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
	<head>
		<script type="text/javascript" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS); ?>advancedmedia/jquery-1.8.3.js"></script>
		<script type="text/javascript" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS); ?>advancedmedia/flowplayer5.3.2.js"></script>
		<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('advancedmedia/css/minimalist.css') ?>" />
	</head>
	<body style="width:100%; height:100%; overflow:hidden">
		<?php echo $this->getChildHtml('content') ?>
	</body>
</html>
