<?php if ( !Mage::getStoreConfig('ajax_pro/general/enabled')
        || !Mage::getStoreConfig('ajax_pro/addToWishlist/enabled')
        || TM_AjaxPro_Model_Action::isSearchBot()
        || !Mage::helper('customer')->isLoggedIn()) {
            return;
        }?>

<script type="text/javascript">
//<![CDATA[
AjaxPro.observe('addObservers', function() {

    setLocation = setLocation.wrap(function(callOriginal, url) {
        if (-1 != url.search('wishlist/index/cart')) {
            return AjaxPro.request({
                'url'    : url,
                'method' : 'post'
            });
        }
        return callOriginal(url);
    });

    $$('a').each(function(element){
        var url = element.getAttribute('href');

        if (url && ((url.search('wishlist/index/add') != -1)
            ||(url.search('wishlist/index/remove') != -1)
                ||(url.search('wishlist/index/cart') != -1)
            ))
        {
            element.stopObserving('click');
            element.setAttribute('onclick', '');
            element.observe('click', function(e) {
                Event.stop(e);
                <?php if (Mage::getStoreConfig('ajax_pro/addToWishlist/enabledDeleteConfirm')) :?>
                if (url.search('wishlist/index/remove') != -1
                    && !confirm('<?php echo Mage::helper('ajaxpro')->__('Are you sure you would like to remove this item from the wishlist?')?>'))
                {
                    return false;
                }
                <?php endif;?>

                AjaxPro.request({
                    'url'    : url,
                    'method' : 'post'
                });
//                if (window.opener) {
//                    window.opener.location.reload(false);
//                }

                return false;
            });
            return false;
        }
    });
});

AjaxPro.observe('onLoading:wishlist', function() {
    AjaxPro.effect.opacity
        .setSelector('.block-wishlist')
        .show(0.5)
    ;
});

AjaxPro.observe('onFailure:wishlist', function() {
    AjaxPro.effect.opacity
        .setSelector('.block-wishlist').hide()
    ;
});

AjaxPro.observe('onComplete:wishlist', function(e) {
    var r = e.memo.response;

    if (r.messages) {
        AjaxPro.effect.message
            .setElementId('ajaxpro-addtowishlist-form')
            .setMessages(r.messages)
            .show()
        ;
    }
});

//]]>
</script>

<?php if (!Mage::getStoreConfig('ajax_pro/addToWishlist/enabledForm')) {
    return;
}?>
<div id ="ajaxpro-addtowishlist-form" class="ajaxpro-form" style="display:none">
    <div class="ajaxpro-message"></div>
    <button class="ajaxpro-continue-button ajaxpro-button button">
        <span><span>
            <?php echo Mage::helper('ajaxpro')->__('Continue shopping')?>
        </span></span>
    </button>
    <p class="ajaxpro-or"><?php echo Mage::helper('ajaxpro')->__('or')?></p>
    <button class="ajaxpro-button button" onclick="setLocation('<?php echo $this->helper('wishlist')->getListUrl() ?>')">
        <span><span>
            <?php echo Mage::helper('ajaxpro')->__('Go to Wishlist');?>
        </span></span>
    </button>
</div>