<?php

if($this->getRequest()->getParam('original_totals', false))    {
    $summary = $this->getChildHtml('totals');
}
else    {
    $summary = $this->getChildHtml('summary');
}



$data = array(
    'shipping_method' => $this->getChildHtml('choose-shipping-method'),
    'payment_method' => $this->getChildHtml('choose-payment-method'),
    'summary' => $summary,
);
$dataBilling = $this->getRequest()->getParam('billing', false);
$dataShipping = $this->getRequest()->getParam('shipping', false);
if (isset($dataBilling['postcode'])) {
    $data['melissa'] = array('billing' => Mage::helper('melissa_address')->searchCityStateAction($dataBilling['postcode'],false),
                             'shipping' => (isset($dataBilling['use_for_shipping']) && $dataBilling['use_for_shipping'] == 1)? false : Mage::helper('melissa_address')->searchCityStateAction($dataShipping['postcode'],false)
    );
}


echo Zend_Json::encode($data);

?>