<?php
$_coreHelper = $this->helper('core');
$checkoutHelper = Mage::helper('onestepcheckout/checkout');
?>

<table class="onestepcheckout-summary">
    <thead>
        <tr>
            <th class="name"><?php echo $this->__('Product'); ?></th>
            <th class="qty"><?php echo $this->__('Qty'); ?></th>
            <th class="total"><?php echo $this->__('Subtotal'); ?></th>
        </tr>
    </thead>
    <?php foreach($this->getItems() as $item):
        $simpleProduct = $item->getOptionByCode('simple_product');
        $simpleProduct = Mage::getModel('catalog/product')->load($item->getProductId());
        $image = $this->helper('catalog/image')->init($simpleProduct, 'thumbnail');
        ?>
    <tr>
        <td class="name">
            <span class="product-image"><img src="<?php echo $image->resize(88,115)->setWatermarkSize('30x10'); ?>" width="88" alt="<?php echo $this->htmlEscape($this->getProductName()) ?>" /></span>
            <?php echo $item->getName(); ?>
            <a href="#" rel="<?php echo $item->getProductId(); ?>-<?php echo $item->getId(); ?>" title="<?php echo $this->__('Edit item parameters') ?>"
                           class="overlay-window btn_edit edit-cart-item"><?php echo $this->__('Edit') ?></a>
            <?php if($checkoutHelper->settings['show_custom_options']): ?>
                <?php $options = $item->getProduct()->getTypeInstance(true)->getOrderOptions($item->getProduct()); ?>
                <?php if(isset($options['options']) && count($options['options']) > 0): ?>
                <ul class="onestepcheckout-custom-options">
                <?php foreach($options['options'] as $option): ?>
                    <li><b><?php echo $option['label'] . ':</b> ' . $option['value']; ?></li>
                <?php endforeach; ?>
                </ul>
                <?php endif; ?>

                <?php if($item->getProduct()->isConfigurable()): ?>

                <?php
                $configurable_options = $item->getProduct()->getTypeInstance(true)->getSelectedAttributesInfo($item->getProduct());
                ?>

                <?php if(is_array($configurable_options) && count($configurable_options) > 0): ?>
                <ul class="onestepcheckout-custom-options">
                <?php foreach($configurable_options as $option): ?>
                    <li><b><?php echo $option['label']; ?>:</b> <?php echo $option['value']; ?></li>
                <?php endforeach; ?>
                </ul>
                <?php endif; ?>

                <?php endif; ?>

            <?php endif; ?>
        </td>
        <td class="qty"><?php echo $item->getQty(); ?></td>
        <td class="total">
            <?php if($checkoutHelper->settings['display_tax_included']): ?>
            <?php echo $this->helper('checkout')->formatPrice($this->helper('checkout')->getSubtotalInclTax($item)); ?>
            <?php else: ?>
            <?php echo $this->helper('checkout')->formatPrice($item->getRowTotal()); ?>
            <?php endif; ?>
        </td>
    </tr>
    <?php endforeach; ?>
</table>

<table class="onestepcheckout-totals">
    <?php foreach($this->getTotals() as $total): ?>
    <?php if(!$total->getTitle()){continue;}?>
        <?php
        $fullInfo = $total->getFullInfo();

        if(!empty($fullInfo) && $checkoutHelper->settings['display_full_tax']):
            foreach ($fullInfo as $info):
                $rates = current($info['rates']);
                $amount = $info['amount'];
        ?>
            <tr>
                <td class="title"><?php echo $rates['title'] ?> (<?php echo $rates['percent'] ?>%)</td><td class="value"><?php echo $this->helper('checkout')->formatPrice($amount); ?></td>
            </tr>
        <?php endforeach;
        endif;?>
    <tr<?php if($total->getCode() == 'grand_total'): ?> class="grand-total"<?php endif; ?>>
        <td class="title">
            <?php

            $code = $total->getCode();
            $value = $total->getValue();

            if($code == 'subtotal')    {
                $total_name = $this->__('Subtotal');
            }
            elseif($code == 'shipping')    {
                $total_name = $this->__('Shipping');
                if($checkoutHelper->settings['display_tax_included'])   {
                    $value += $this->getQuote()->getShippingAddress()->getShippingTaxAmount();
                }
                            }
            elseif($code == 'grand_total')    {
                $total_name = $this->__('Grand total');
            }
            else    {
                $total_name = $total->getTitle();
            }

            echo $total_name;

            ?>
        </td>
        <td class="value">
            <?php echo $this->helper('checkout')->formatPrice($value); ?>
        </td>
    </tr>
    <?php endforeach; ?>
</table>
<script type="text/javascript">
//<![CDATA[
var total = <?php echo $this->getGrandTotal();?>;
    if(payment.reloadcallback){
        var url = '<?php echo $this->getUrl('onestepcheckout/ajax/paymentrefresh', array('_secure'=>true)); ?>';
        paymentrefresh(url);
        payment.countreload = 0;
        payment.reloadcallback = false;
    }
//]]>
</script>
<script type="text/javascript">
    (function($) {
        $(function() {

            $('.edit-cart-item').each(function() {
                var link = $(this),
                    rel = link.attr('rel'), tmp = rel.split('-');

                var productId = tmp[0],
                    itemId    = tmp[1];

                var editUrl = '<?php echo $this->getUrl('quickbox/product/edit', array('_secure'=>true)); ?>';

                link.fancybox({
                    maxWidth	: 800,
                    maxHeight	: 600,
                    fitToView	: false,
                    width		: '70%',
                    height		: '70%',
                    autoSize	: false,
                    closeClick	: false,
                    openEffect	: 'none',
                    closeEffect	: 'none',
                    type: 'ajax',
                    href: editUrl + '?id=' + productId + '&item=' + itemId + '&area=checkout'
                });
            });
        });
    })(jQuery);
</script>
