<?php
$_coreHelper = $this->helper('core');
$checkoutHelper = Mage::helper('onestepcheckout/checkout');
?>
<div class="<?php if (count($this->getItems()) > 2):?>scroll-pane<?php endif;?>">
<ul class="onestepcheckout-summary scroll-content">
    
    <?php foreach($this->getItems() as $item):
        $simpleProduct = $item->getOptionByCode('simple_product');
        $simpleProduct = Mage::getModel('catalog/product')->load($item->getProductId());
        $image = $this->helper('catalog/image')->init($simpleProduct, 'thumbnail');
        ?>
    <li>
		<div class="product-image"><img src="<?php echo $image->resize(75,119)->setWatermarkSize('30x10'); ?>" alt="<?php echo $this->htmlEscape($this->getProductName()) ?>" /></div>
        <div class="product-detail">            
            <h3 class="product-name"><?php echo $item->getName(); ?></h3>
            
            <?php if($checkoutHelper->settings['show_custom_options']): ?>
                <?php $options = $item->getProduct()->getTypeInstance(true)->getOrderOptions($item->getProduct()); ?>
                <?php if(isset($options['options']) && count($options['options']) > 0): ?>
                <ul class="onestepcheckout-custom-options">
                <?php foreach($options['options'] as $option): ?>
                    <li><b><?php echo $option['label'] . ':</b> ' . $option['value']; ?></li>
                <?php endforeach; ?>
                </ul>
                <?php endif; ?>

                <?php if($item->getProduct()->isConfigurable()): ?>

                <?php
                $configurable_options = $item->getProduct()->getTypeInstance(true)->getSelectedAttributesInfo($item->getProduct());
                ?>

                <?php if(is_array($configurable_options) && count($configurable_options) > 0): ?>
                <ul class="onestepcheckout-custom-options">
                <?php foreach($configurable_options as $option): ?>
                    <li>
						<span class="label"><?php echo $option['label']; ?>:</span> 
						<span class="value"><?php echo $option['value']; ?></span> 
					</li>
                <?php endforeach; ?>
                </ul>
                <?php endif; ?>

                <?php endif; ?>

            <?php endif; ?>
			<div class="osc-cart-quantity">
				<span class="label"><?php echo $this->__('Qty'); ?>:</span>
				<span class="value"><?php echo $item->getQty(); ?></span>
			</div>
			<div class="osc-event_date">
				<span class="label"><?php echo $this->__('Event Date'); ?>:</span>
				<div class="value">
					<img title="Select date" id="event_date_trig_<?php echo $item->getProductId(); ?>" src="<?php echo $this->getSkinUrl('images/calendar.gif');?>" class="v-middle">
					<input type="text" id="event_date_<?php echo $item->getProductId(); ?>" name="event_date[<?php echo $item->getProductId(); ?>]" class="input-text required-entry" size="5"/>
					
				</div>
				<script type="text/javascript">
					//<![CDATA[
					Calendar.setup({
						inputField : 'event_date_<?php echo $item->getProductId(); ?>',
						ifFormat : '%m/%e/%y',
						button : 'event_date_trig_<?php echo $item->getProductId(); ?>',
						align : 'Bl',
						singleClick : true
					});
					//]]>
				</script>
			</div>
			<div class="total">
				<?php if($checkoutHelper->settings['display_tax_included']): ?>
				<?php echo $this->helper('checkout')->formatPrice($this->helper('checkout')->getSubtotalInclTax($item)); ?>
				<?php else: ?>
				<?php echo $this->helper('checkout')->formatPrice($item->getRowTotal()); ?>
				<?php endif; ?>
			</div>
        </div>
		<a href="#" onclick="removeItemInCheckOut(<?php echo $item->getProductId(); ?>);return false;" title="<?php echo $this->__('Remove item')?>" class="btn-remove btn-remove3"><?php echo $this->__('Remove item')?></a>
    </li>
    <?php endforeach; ?>
</ul>
</div>
<table class="onestepcheckout-totals">
    <?php foreach($this->getTotals() as $total): ?>
    <?php if(!$total->getTitle()){continue;}?>
        <?php
        $fullInfo = $total->getFullInfo();

        if(!empty($fullInfo) && $checkoutHelper->settings['display_full_tax']):
            foreach ($fullInfo as $info):
                $rates = current($info['rates']);
                $amount = $info['amount'];
        ?>
            <tr>
                <td class="title"><?php echo $rates['title'] ?> (<?php echo $rates['percent'] ?>%)</td><td class="value"><?php echo $this->helper('checkout')->formatPrice($amount); ?></td>
            </tr>
        <?php endforeach;
        endif;?>
    <tr<?php if($total->getCode() == 'grand_total'): ?> class="grand-total"<?php endif; ?>>
        <td class="title">
            <?php

            $code = $total->getCode();
            $value = $total->getValue();

            if($code == 'subtotal')    {
                $total_name = $this->__('Subtotal');
            }
            elseif($code == 'shipping')    {
                $total_name = $this->__('Shipping');
                if($checkoutHelper->settings['display_tax_included'])   {
                    $value += $this->getQuote()->getShippingAddress()->getShippingTaxAmount();
                }
                            }
            elseif($code == 'grand_total')    {
                $total_name = $this->__('Grand total');
            }
            else    {
                $total_name = $total->getTitle();
            }

            echo $total_name;

            ?>
        </td>
        <td class="value">
            <?php echo $this->helper('checkout')->formatPrice($value); ?>
        </td>
    </tr>
    <?php endforeach; ?>
</table>
<script type="text/javascript">
//<![CDATA[
var total = <?php echo $this->getGrandTotal();?>;
    if(payment.reloadcallback){
        var url = '<?php echo $this->getUrl('onestepcheckout/ajax/paymentrefresh', array('_secure'=>true)); ?>';
        paymentrefresh(url);
        payment.countreload = 0;
        payment.reloadcallback = false;
    }
//]]>
</script>
<script type="text/javascript">
    function removeItemInCheckOut(id){
        var url = '<?php echo $this->getUrl("onestepcheckout/ajax/removeItem"); ?>';
        var summary = $$('div.onestepcheckout-summary').first();
        summary.update('<div class="loading-ajax">&nbsp;</div>');
        var parameters = {item: id};
            new Ajax.Request(url, {
                method: 'post',
                parameters: parameters,
                onSuccess: function(transport) {
                    if(transport.status == 200) {
                        var response = transport.responseText.evalJSON();
                        if(response.checkout) {
                            location.reload();
                        }
                        else    {
                            summary.update(response.summary);
                        }
                    }
                }
            });
    }

    jQuery(document).ready(function(){
        jQuery('.scroll-pane').jScrollPane();
        if(jQuery("#p_method_paypal_express").is(":checked")) {
            jQuery('#onestepcheckout-place-order span span').text('<?php echo $this->__("Continue With Paypal"); ?>');
        }else{
            jQuery('#onestepcheckout-place-order span span').text('<?php echo $this->__("Place Order Now"); ?>');
        }
    });
    (function($) {
        $(function() {

            $('.edit-cart-item').each(function() {
                var link = $(this),
                    rel = link.attr('rel'), tmp = rel.split('-');

                var productId = tmp[0],
                    itemId    = tmp[1];

                var editUrl = '<?php echo $this->getUrl('quickbox/product/edit', array('_secure'=>true)); ?>';

                link.fancybox({
                    closeClick: false,
                    type: 'ajax',
                    href: editUrl + '?id=' + productId + '&item=' + itemId + '&area=checkout'
                });
            });
        });
    })(jQuery);
</script>
